### PR TITLE
Fix failing unit test.

### PR DESCRIPTION
**Pull request by gbrownmozilla**

### CODE REVIEW

**Review by jmaher — COMMENTED** [review]
is this a side effect to the change you made?  Somehow this was working previously

**Comment by gbrownmozilla** [comment]
I don't see how it could be. I think it was broken before, somehow.

**Comment by gbrownmozilla** [comment]
Without this fix, it fails for me like:
```
____________________________________________ test_sign_file_badfile ____________________________________________

tmp_path = PosixPath('/tmp/pytest-of-gbrown/pytest-7/test_sign_file_badfile0')
signing_keys = (PosixPath('/home/gbrown/winsign/tests/data/privkey.pem'), PosixPath('/home/gbrown/winsign/tests/data/cert.pem'))

    @pytest.mark.asyncio
    async def test_sign_file_badfile(tmp_path, signing_keys):
        """Verify that we can't sign non-exe files."""
        test_file = Path(__file__)
        signed_file = tmp_path / "signed.py"
    
        priv_key = load_private_key(open(signing_keys[0], "rb").read())
        certs = load_pem_certs(signing_keys[1].read_bytes())
        cafile = signing_keys
        tsfile = '/etc/ssl/certs/ca-certificates.crt'
    
        async def signer(digest, digest_algo):
            return sign_signer_digest(priv_key, digest_algo, digest)
    
>       assert not await sign_file(test_file, signed_file, "sha1", certs, signer, cafile, tsfile)

tests/test_osslsigncode.py:156: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/winsign/sign.py:93: in sign_file
    if not is_msix and (cafile is None or not Path(cafile).is_file()):
/usr/lib/python3.8/pathlib.py:1042: in __new__
    self = cls._from_parts(args, init=False)
/usr/lib/python3.8/pathlib.py:683: in _from_parts
    drv, root, parts = self._parse_args(args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'pathlib.PosixPath'>
args = ((PosixPath('/home/gbrown/winsign/tests/data/privkey.pem'), PosixPath('/home/gbrown/winsign/tests/data/cert.pem')),)

    @classmethod
    def _parse_args(cls, args):
        # This is useful when you don't want to create an instance, just
        # canonicalize some constructor arguments.
        parts = []
        for a in args:
            if isinstance(a, PurePath):
                parts += a._parts
            else:
>               a = os.fspath(a)
E               TypeError: expected str, bytes or os.PathLike object, not tuple

/usr/lib/python3.8/pathlib.py:667: TypeError

```

**Review by jmaher — APPROVED** [review]
this is a bit of brute force as well.  I was pretty sure I had everything working and green back in October, but if it is failing, then obviously we need this fix.  Thanks!

**Pull request merged**
